<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getData, postData, putData, type ServerPage } from '../api/database'
import { currentUser } from './auth'
import { time, type Options } from './types'
import type { User } from './auth'
const props = defineProps<{ mode: string }>(); const users = ref<ServerPage<User>>(), options = ref<Options>({ categories: [], tags: [] }), q = ref(''), page = ref(1), loading = ref(false), error = ref(''), notice = ref(''), name = ref(''), kind = ref('categories')
const renameTarget = ref<{ type: string; id: number; name: string }>(), renameValue = ref('')
let requestVersion = 0
async function load() { const version = ++requestVersion; loading.value = true; error.value = ''; try { if (props.mode === 'users') { const result = await getData<ServerPage<User>>('/admin/users', { q: q.value, page: page.value, size: 10 }); if (version === requestVersion) { users.value = result; page.value = result.page } } else if (props.mode === 'taxonomy') { const result = await getData<Options>('/account/options'); if (version === requestVersion) options.value = result } } catch (e) { if (version === requestVersion) error.value = (e as Error).message } finally { if (version === requestVersion) loading.value = false } }
async function add() { loading.value = true; error.value = ''; try { options.value = await postData(`/admin/${kind.value}`, { name: name.value }); name.value = ''; notice.value = '已添加。' } catch (e) { error.value = (e as Error).message } finally { loading.value = false } }
function rename(type: string, item: { id: number; name: string }) { renameTarget.value = { type, ...item }; renameValue.value = item.name }
async function saveName() { const item = renameTarget.value; if (!item) return; loading.value = true; error.value = ''; try { options.value = await putData(`/admin/${item.type}/${item.id}`, { name: renameValue.value }); notice.value = '已更新名称，原有引用已保留。'; renameTarget.value = undefined } catch (e) { error.value = (e as Error).message } finally { loading.value = false } }
onMounted(load)
</script>
<template>
  <header class="account-heading"><div><span class="account-eyebrow">ACCOUNT WORKSPACE</span><h1>{{ mode === 'profile' ? '个人资料' : mode === 'users' ? '用户列表' : mode === 'taxonomy' ? '分类与标签' : '页面不存在' }}</h1></div><RouterLink v-if="mode !== 'profile'" class="account-button" to="/admin">返回控制台</RouterLink></header>
  <p class="account-feedback" :class="{ error }" role="status">{{ error || notice }} <button v-if="error" class="account-text-button" @click="load">重试</button></p>
  <section v-if="mode === 'profile'" class="account-card"><dl class="account-profile"><dt>显示名称</dt><dd>{{ currentUser?.displayName }}</dd><dt>用户名</dt><dd>{{ currentUser?.username }}</dd><dt>角色</dt><dd>{{ currentUser?.role === 'ADMIN' ? '管理员' : '普通用户' }}</dd><dt>注册时间</dt><dd>{{ time(currentUser?.createdAt) }}</dd></dl><p class="account-muted">邮箱验证、找回密码和资料修改暂未开放。</p><a class="account-button" href="./oj.html">前往题库</a><p class="account-muted">OJ 仍为独立演示流程，演示 AC 不计入真实练习统计。</p></section>
  <section v-else-if="mode === 'users'" class="account-card"><form class="account-filters" @submit.prevent="page = 1; load()"><label>搜索真实账户<input v-model="q" placeholder="用户名或显示名称" maxlength="100" /></label><button class="account-button" :disabled="loading">搜索</button><button type="button" class="account-text-button" @click="q = ''; page = 1; load()">清除筛选</button></form><p v-if="loading && !users" aria-busy="true">正在加载用户…</p><div v-else-if="users?.total === 0" class="account-empty">没有符合条件的用户。</div><div class="account-user-list" :aria-busy="loading"><article v-for="user in users?.items" :key="user.id"><div><h2>{{ user.displayName }}</h2><p>@{{ user.username }}</p><small>注册时间 {{ time(user.createdAt) }}</small></div><span class="account-badge">{{ user.role === 'ADMIN' ? '管理员' : '普通用户' }}</span></article></div><footer v-if="users" class="account-pagination"><span>共 {{ users.total }} 个真实账户</span><button class="account-button" :disabled="loading || page <= 1" @click="page--; load()">上一页</button><span>{{ users.page }} / {{ users.pages }}</span><button class="account-button" :disabled="loading || page >= users.pages" @click="page++; load()">下一页</button></footer></section>
  <template v-else-if="mode === 'taxonomy'"><section class="account-card"><form class="account-filters" @submit.prevent="add"><label>类型<select v-model="kind"><option value="categories">文章分类</option><option value="tags">共享算法标签</option></select></label><label>新名称<input v-model="name" required maxlength="64" /></label><button class="account-button primary" :disabled="loading">添加</button></form><p class="account-muted">共享标签也用于题库。重命名保留关联；本次不删除被使用的分类或标签。</p></section><section v-if="renameTarget" class="account-card"><h2>重命名 {{ renameTarget.name }}</h2><p>引用此条目的历史文章和题目会显示新名称。</p><form class="account-filters" @submit.prevent="saveName"><label>修改名称<input v-model="renameValue" required maxlength="64" /></label><button class="account-button primary" :disabled="loading">保存名称</button><button type="button" class="account-button" @click="renameTarget = undefined">取消</button></form></section><div class="account-taxonomy-grid"><section v-for="(items, type) in options" :key="type" class="account-card"><h2>{{ type === 'categories' ? '文章分类' : '共享算法标签' }}</h2><ul><li v-for="item in items" :key="item.id"><span>{{ item.name }}</span><button class="account-text-button" :disabled="loading" @click="rename(type, item)">重命名</button></li></ul></section></div></template>
  <section v-else class="account-card account-empty"><p>链接不存在，请返回用户中心。</p><RouterLink to="/articles">我的文章</RouterLink></section>
</template>
