import type { Problem } from './types'

const template = (setup: string) => `#include <iostream>\n#include <vector>\nusing namespace std;\n\nint main() {\n    ios::sync_with_stdio(false);\n    cin.tie(nullptr);\n\n${setup}\n    // TODO: 根据题目要求实现算法和输出。\n\n    return 0;\n}\n`
const base = { timeLimit: 1000, memoryLimit: 256, source: 'ACM Code Share 演示题库' }
export const problems: Problem[] = [
  { ...base, id: 'P1001', title: 'A+B Problem', difficulty: '简单', tags: ['基础', '数学'],
    description: '给定两个整数 a 和 b，计算它们的和。', input: '一行两个整数 a、b，以空格分隔。', output: '输出一个整数，表示 a+b。',
    samples: [{ input: '3 5', output: '8', explanation: '3+5=8。' }, { input: '-2 7', output: '5', explanation: '-2+7=5。' }],
    constraints: ['−10⁹ ≤ a,b ≤ 10⁹。建议使用 long long。'], template: template('    long long a, b;\n    if (!(cin >> a >> b)) return 0;'), articleIds: [] },
  { ...base, id: 'P1008', title: '数组元素和', difficulty: '简单', tags: ['数组', '基础'],
    description: '给定 n 个整数，求所有元素的和。', input: '第一行一个整数 n，第二行 n 个整数。', output: '输出所有元素之和。',
    samples: [{ input: '5\n1 2 3 4 5', output: '15', explanation: '1+2+3+4+5=15。' }], constraints: ['1 ≤ n ≤ 10⁵', '每个整数的绝对值不超过 10⁹，使用 long long。'],
    template: template('    int n;\n    if (!(cin >> n)) return 0;\n    vector<long long> a(n);\n    for (auto &x : a) cin >> x;'), articleIds: [8] },
  { ...base, id: 'P1015', title: '排序', difficulty: '简单', tags: ['排序', '基础'],
    description: '将 n 个整数按非递减顺序排序。重复的数字需要全部保留。', input: '第一行 n，第二行 n 个整数。', output: '一行输出排序后的 n 个整数，以空格分隔。',
    samples: [{ input: '5\n4 1 3 1 2', output: '1 1 2 3 4', explanation: '按数值从小到大排列，保留两个 1。' }], constraints: ['1 ≤ n ≤ 10⁵', '每个整数的绝对值不超过 10⁹。'],
    template: template('    int n;\n    if (!(cin >> n)) return 0;\n    vector<int> a(n);\n    for (auto &x : a) cin >> x;'), articleIds: [8] },
  { ...base, id: 'P1032', title: '最短路', difficulty: '中等', tags: ['图论', '最短路', 'Dijkstra'],
    description: '给定 n 个点、m 条边的有向图，边权均为非负整数。求起点 s 到所有点的最短距离。顶点编号为 1 到 n；不可达的点输出 −1。',
    input: '第一行三个整数 n、m、s。接下来 m 行，每行三个整数 u、v、w，表示从 u 到 v 的有向边，权重为 w。允许重边和自环。',
    output: '输出一行 n 个整数，第 i 个整数表示从 s 到 i 的最短距离。不可达时输出 −1，整数间用空格分隔。',
    samples: [{ input: '5 6 1\n1 2 2\n1 3 5\n2 3 1\n2 4 2\n3 4 3\n4 5 1', output: '0 2 3 4 5', explanation: '从 1 出发，到 3 的最短路为 1→2→3，到 5 为 1→2→4→5。' },
      { input: '3 1 2\n2 3 4', output: '-1 0 4', explanation: '起点为 2，不能到达顶点 1。' }],
    constraints: ['1 ≤ n ≤ 10⁵，0 ≤ m ≤ 2×10⁵', '1 ≤ s,u,v ≤ n，0 ≤ w ≤ 10⁹', '距离累加可能超过 int 范围。建议采用堆优化 Dijkstra。'],
    template: template('    int n, m, s;\n    if (!(cin >> n >> m >> s)) return 0;\n    // 顶点编号为 1 到 n；读取 m 条有向边。'), articleIds: [1] },
  { ...base, id: 'P1048', title: '01 背包', difficulty: '中等', tags: ['动态规划', '背包'],
    description: '有 n 件物品，每件只能选择一次。背包容量为 C，求总体积不超过 C 时的最大总价值。', input: '第一行 n、C。接下来 n 行，每行物品体积 w 和价值 v。', output: '输出最大总价值；可以不选择任何物品。',
    samples: [{ input: '3 5\n2 3\n3 4\n4 5', output: '7', explanation: '选择前两件物品，总体积 5，总价值 7。' }], constraints: ['1 ≤ n ≤ 1000，1 ≤ C ≤ 1000', '1 ≤ w ≤ C，0 ≤ v ≤ 10⁶。'],
    template: template('    int n, capacity;\n    if (!(cin >> n >> capacity)) return 0;'), articleIds: [3] },
  { ...base, id: 'P1060', title: '并查集', difficulty: '中等', tags: ['并查集', '数据结构'],
    description: '初始有 n 个独立元素。处理合并集合与连通性查询。', input: '第一行 n、q。接下来 q 行 op、u、v：op=1 合并 u、v 所在集合；op=2 查询两者是否同一集合。', output: '每个查询输出一行 Yes 或 No，大小写需一致。',
    samples: [{ input: '4 5\n2 1 2\n1 1 2\n2 1 2\n1 2 3\n2 1 3', output: 'No\nYes\nYes', explanation: '第一次查询未连接；合并后，1、2、3 属于同一集合。' }], constraints: ['1 ≤ n,q ≤ 2×10⁵', '1 ≤ u,v ≤ n。'],
    template: template('    int n, q;\n    if (!(cin >> n >> q)) return 0;'), articleIds: [2] },
  { ...base, id: 'P1088', title: 'KMP 字符串匹配', difficulty: '困难', tags: ['字符串', 'KMP'],
    description: '统计模式串在文本中出现的次数，允许匹配位置重叠。', input: '第一行文本，第二行模式串；均为非空小写英文字母串。', output: '输出模式串出现的次数。',
    samples: [{ input: 'aaaaa\naaa', output: '3', explanation: '匹配起始位置为 1、2、3，重叠的匹配也计入。' }], constraints: ['两个字符串长度均不超过 10⁶。'],
    template: template('    string text, pattern;\n    if (!(cin >> text >> pattern)) return 0;'), articleIds: [5] },
  { ...base, id: 'P1099', title: '最小生成树', difficulty: '困难', tags: ['图论', '最小生成树', '贪心'],
    description: '给定 n 个点、m 条边的无向图，求连接所有点的最小生成树的边权总和。若无法连接所有点，输出 −1。', input: '第一行 n、m，接下来 m 行 u、v、w，表示无向边和边权。', output: '输出最小生成树边权总和，不存在则输出 −1。',
    samples: [{ input: '3 3\n1 2 1\n2 3 2\n1 3 4', output: '3', explanation: '选择权重为 1 和 2 的边，总权重为 3。' }], constraints: ['1 ≤ n ≤ 10⁵，0 ≤ m ≤ 2×10⁵', '1 ≤ u,v ≤ n，0 ≤ w ≤ 10⁹。'],
    template: template('    int n, m;\n    if (!(cin >> n >> m)) return 0;'), articleIds: [2] },
]
