acm.db.host=${DB_HOST}
acm.db.port=${DB_PORT}
acm.db.name=${DB_NAME}
acm.db.username=${DB_USER}
acm.db.password=${DB_PASSWORD}
acm.db.action=${DB_ACTION:serve}
acm.db.truststore-path=${DB_TRUSTSTORE_PATH:}
acm.db.truststore-password=${DB_TRUSTSTORE_PASSWORD:}
acm.db.pool-timeout-ms=${DB_POOL_TIMEOUT_MS:30000}
acm.db.pool-max-lifetime-ms=${DB_POOL_MAX_LIFETIME_MS:120000}
acm.db.pool-idle-timeout-ms=${DB_POOL_IDLE_TIMEOUT_MS:60000}
acm.db.pool-keepalive-ms=${DB_POOL_KEEPALIVE_MS:30000}
