acm.db.host=${DB_HOST}
acm.db.port=${DB_PORT}
acm.db.name=${DB_NAME}
acm.db.username=${DB_USER}
acm.db.password=${DB_PASSWORD}
acm.db.action=${DB_ACTION:serve}
acm.db.truststore-path=${DB_TRUSTSTORE_PATH:}
acm.db.truststore-password=${DB_TRUSTSTORE_PASSWORD:}
acm.db.pool-timeout-ms=${DB_POOL_TIMEOUT_MS:30000}
